# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nikhil Ikhar
email: "nikhil.ikhar@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Many things about Aritficial Intelligence, Pytorch & Fastai
#baseurl: "" # the subpath of your site, e.g. /blog

# the base hostname & protocol for your site, e.g. http://example.com
# used with jekyll-sitemap
url: "https://nik-hil.github.io" 
github_username:  nik-hil
linkedin_username:    nikhar
google_analytics:   UA-140656569-1

repository_url: "https://github.com/nik-hil"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-tagging-related_posts

show_excerpts: true

# syntax hightlighting 
# https://mycyberuniverse.com/syntax-highlighting-jekyll.html
highlighter: rouge


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include: [_pages]
